name: CD za Studiranje app

on:
  workflow_run:
    workflows: ["CI za Studiranje"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy app
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Deploy
        run: flyctl deploy --remote-only --app laravel-studiranje-app-mk1
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}